# Generated by Django 2.0.3 on 2018-08-28 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZA_UserInfo',
            fields=[
                ('ZA_User_ID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('ZA_User_RegTime', models.DateField(default=datetime.date.today, verbose_name='用户注册时间')),
                ('ZA_User_Email', models.CharField(default='', max_length=100, unique=True, verbose_name='电子邮箱')),
                ('ZA_User_Phone', models.CharField(blank=True, default='', max_length=11, verbose_name='联系电话')),
                ('ZA_User_Name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('ZA_User_Password', models.CharField(default='', max_length=65, verbose_name='密码')),
                ('ZA_User_motto', models.CharField(blank=True, default='', max_length=60, verbose_name='个性签名')),
                ('ZA_User_StudentID', models.CharField(blank=True, default='', max_length=12, verbose_name='学号')),
                ('ZA_User_Faculty', models.CharField(blank=True, default='校外人士', max_length=60, verbose_name='院系')),
                ('ZA_User_Campus', models.CharField(blank=True, default='校外人士', max_length=60, verbose_name='校区')),
                ('ZA_User_Birthday', models.CharField(blank=True, default='', max_length=60, verbose_name='出生日期')),
                ('ZA_User_Sex', models.CharField(blank=True, default='雌雄同体', max_length=8, verbose_name='性别')),
                ('ZA_User_identity', models.CharField(default='0', max_length=2, verbose_name='用户身份')),
                ('ZA_User_FromIP', models.CharField(blank=True, default='IPUnknow', max_length=20, verbose_name='用户登录IP')),
                ('ZA_User_HeaderImg', models.ImageField(blank=True, default='/ZA_User/img/HeaderImg/default.jpg', upload_to='ZA_User/img/HeaderImg', verbose_name='用户头像')),
                ('ZA_User_Action', models.CharField(default='0', max_length=6, verbose_name='用户状态')),
            ],
        ),
    ]
