# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZA_UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZA_User_RegTime', models.CharField(default='', max_length=100)),
                ('ZA_User_Email', models.CharField(default='', max_length=100)),
                ('ZA_User_Phone', models.CharField(default='', max_length=11)),
                ('ZA_User_Name', models.CharField(max_length=20, unique=True)),
                ('ZA_User_Password', models.CharField(default='', max_length=60)),
                ('ZA_User_motto', models.CharField(default='', max_length=60)),
                ('ZA_User_Specialty', models.CharField(default='', max_length=40)),
                ('ZA_User_StudentID', models.CharField(default='', max_length=12)),
                ('ZA_User_Class', models.CharField(default='', max_length=60)),
                ('ZA_User_Faculty', models.CharField(default='', max_length=60)),
                ('ZA_User_Campus', models.CharField(default='', max_length=60)),
                ('ZA_User_Birthday', models.CharField(default='', max_length=60)),
                ('ZA_User_Age', models.CharField(default='', max_length=60)),
                ('ZA_User_Sex', models.CharField(default='雌雄同体', max_length=60)),
                ('ZA_User_Constellation', models.CharField(default='肉座的', max_length=20)),
                ('ZA_User_HomeTown', models.CharField(default='', max_length=20)),
                ('ZA_User_Medal', models.CharField(default='', max_length=20)),
                ('ZA_User_Department', models.CharField(default='咸鱼部', max_length=20)),
                ('ZA_User_identity', models.CharField(default='0', max_length=20)),
                ('ZA_User_Permission', models.CharField(default='0', max_length=20)),
                ('ZA_User_FromIP', models.CharField(default='IPUnknow', max_length=20)),
                ('ZA_User_HeaderImg', models.CharField(default='default.img', max_length=200)),
                ('ZA_User_Action', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
